allowBuilds:
  esbuild: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - hono@4.12.32 || 4.12.33
  - '@cloudflare/workers-types@5.20260731.1'
  - miniflare@5.20260730.0-alpha
  - wrangler@4.118.0
